/**
* Author: Anjali Bhusarapu
* Created Date: 21-03-2024
* Description: This class contains constant variables.
**/
public class CQ_Constant_Variables {

        public static final String PART_SETTING_NAME = 'Part_Settings',
                                   NO_CONFIGURATION_MESSAGE = 'No Configuration Found, Please set up the configuration',
                                   RESPONSE_PART_ID = '_id',
                                   RESPONSE_PART_NAME = 'Part Name',
                                   RESPONSE_TOTAL_QUANTITY_SHIPPED = 'Total Quantity Shipped',
                                   HIGH_VOLUME = 'High Volume',
                                   LOW_VOLUME = 'Low Volume';
}